# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-06-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20210602_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='Updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
